#pragma once

#if defined(NDEBUG)
#define VNLB_INTERNAL_VALIDATION_ENABLED 0
#define VNLB_INTERNAL_VALIDATION_NOEXCEPT noexcept
#else
#define VNLB_INTERNAL_VALIDATION_ENABLED 1
#define VNLB_INTERNAL_VALIDATION_NOEXCEPT
#endif
